name: Plentiful_harvest
version: '${project.version}'
main: me.glasscrab.plentiful_harvest.PlentifulHarvest
api-version: 1.20
authors: [ glasscrab, JamieIsGeek ]
description: Farming plugin for sootsmp

commands:
  givecrop:
    usage: /<command> <crop> <player> <amount>
    default: op